import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBarComponent from "@/components/navBar/NavBarComponent";
import FooterComponent from "@/components/footer/FooterComponent";

import "./globals.css";
import Title from "@/components/title/Title";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Club El Tropezón",
  description: "Generated by Noelia Camelia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBarComponent />
        <Title />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
